name: Testing on pull requests
on:
  pull_request:
    types: [opened, synchronize, edited]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Test the code
        run: yarn test
